
language: cpp

sudo: required

compiler:
  - clang

env:
  - COMPILER=clang++-3.9

os:
  - linux

install:
  - sudo apt-get install sqlite3 libsqlite3-dev clang++-3.9

script:
  - CXX -std=c++14 examples/in_memory.cpp -I include/sqlite_orm/ -lsqlite3