
language: cpp

sudo: required

compiler:
  - clang

#env:
#  - COMPILER=clang++-3.9

os:
  - linux

install:
  - sudo apt-get install sqlite3 libsqlite3-dev

script:
  - CXX -std=c++1z examples/in_memory.cpp -I include/sqlite_orm/ -lsqlite3