# Copyright (c) 2012-2019 Sebastien Rombauts (sebastien.rombauts@gmail.com)

# build format
version: "{build}"

image:
  - Visual Studio 2017
  
# configurations to add to build matrix
# TODO: MinGW Makefiles and MSYS Makefiles
configuration:
  - Debug
  - Release

platform:
  - x86
  - x64

init:
  - echo %APPVEYOR_BUILD_WORKER_IMAGE% - %configuration% - %PLATFORM%
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" (set generator="Visual Studio 16 2019")
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" (set generator="Visual Studio 15 2017")
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" (set generator="Visual Studio 14 2015")
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" (set generator="Visual Studio 12 2013")
  - if "%PLATFORM%"=="x64" (set architecture=-A x64)
  - if "%PLATFORM%"=="x86" (set architecture=-A Win32)

install:
  - C:\Tools\vcpkg\vcpkg integrate install
  - vcpkg install catch2:%PLATFORM%-windows

# scripts to run before build
before_build:
  - mkdir compile
  - cd compile
  - cmake -DSqliteOrm_BuildTests=ON .. -G %generator% %architecture%

# build examples, and run tests (ie make & make test)
build_script:
  - cmake --build . --config %configuration%
  - ctest --output-on-failure --build-config %configuration%
